fix: MDP-3305 UI for migration
Mentor-Medier/arc-to-ntb-uploader pull request #5
Opened 2023-06-06 06:35 UTC by sheikhimtiaz-cefalo

2023-06-06 09:24 UTC, sultanmahmud0 requested changes

2023-06-06 09:24 UTC, sultanmahmud0 commented on src/main/resources/application-development.yml
> +    dagen: 64094424-24a7-4df2-98a6-702e15517009
Are these production Ids ? I think in the application-development file we should have the Ids of sandbox, not production.

2023-06-06 09:24 UTC, sultanmahmud0 commented on src/main/resources/application.yml
> +    dagen: 64094424-24a7-4df2-98a6-702e15517009
Are these production Ids ? Also, I guess we should put the Id for morgenbladet.

2023-06-06 09:53 UTC, sheikhimtiaz-cefalo commented on src/main/resources/application.yml
> +    dagen: 64094424-24a7-4df2-98a6-702e15517009
FIxed it.

2023-06-09 08:59 UTC, sheikhimtiaz-cefalo reviewed
Fixed it

2023-06-09 08:59 UTC, sheikhimtiaz-cefalo commented on src/main/java/no/mentordigital/arctontbuploader/webclient/arc/ArcReaderClient.java
> +        if (affiliation.getName().contains(SCANPIX) || affiliation.getName().contains(NTB)) {
Fixed it.

2023-06-09 08:59 UTC, sheikhimtiaz-cefalo commented on src/main/java/no/mentordigital/arctontbuploader/webclient/arc/ArcReaderClient.java
> +        if ((!Objects.isNull(by.getByline()) && !Objects.isNull(by.getName()))
Fixed it.

2023-06-09 08:59 UTC, sheikhimtiaz-cefalo commented on src/main/java/no/mentordigital/arctontbuploader/webclient/arc/model/ImageInStory.java
> +        .isSuccess(false)
We are not exporting anything, we are keeping this information initially and updating it once we have migrated the image. Fixed it.

2023-06-15 07:14 UTC, sultanmahmud0 approved these changes
Looks good

2023-06-15 07:22 UTC, merged